;METADATA=(Diff=true, UseCommands=true)
[/Script/GameplayTags.GameplayTagsSettings]
ImportTagsFromConfig=True
WarnOnInvalidTags=True
ClearInvalidTags=False
AllowEditorTagUnloading=True
AllowGameTagUnloading=False
FastReplication=False
bDynamicReplication=False
InvalidTagCharacters="\"\',"
NumBitsForContainerSize=6
NetIndexFirstBitSegment=16
+GameplayTagList=(Tag="Cooldown.Blink",DevComment="")
+GameplayTagList=(Tag="Cooldown.Clone",DevComment="")
+GameplayTagList=(Tag="Cooldown.Grapple",DevComment="")
+GameplayTagList=(Tag="Cooldown.Jump",DevComment="")
+GameplayTagList=(Tag="Cooldown.Sprint",DevComment="")
+GameplayTagList=(Tag="Data.Jump.Cooldown",DevComment="")
+GameplayTagList=(Tag="Data.PlayerID",DevComment="")
+GameplayTagList=(Tag="Event.Ability.Changed",DevComment="")
+GameplayTagList=(Tag="Event.ActivateAbility.Blink",DevComment="")
+GameplayTagList=(Tag="Event.ActivateAbility.Clone",DevComment="")
+GameplayTagList=(Tag="Event.ActivateAbility.Jump",DevComment="")
+GameplayTagList=(Tag="Event.ActivateAbility.WallRun",DevComment="")
+GameplayTagList=(Tag="Event.ActivateAbility.WallRun.Start",DevComment="")
+GameplayTagList=(Tag="Event.ActivateAbility.WallRun.Stop",DevComment="")
+GameplayTagList=(Tag="Event.Anim.Throw",DevComment="")
+GameplayTagList=(Tag="Gameplay.Ability.Blink",DevComment="")
+GameplayTagList=(Tag="Gameplay.Ability.Clone",DevComment="")
+GameplayTagList=(Tag="Gameplay.Ability.Crouch",DevComment="")
+GameplayTagList=(Tag="Gameplay.Ability.Grapple",DevComment="")
+GameplayTagList=(Tag="Gameplay.Ability.Jump",DevComment="")
+GameplayTagList=(Tag="Gameplay.Ability.Sprint",DevComment="")
+GameplayTagList=(Tag="Gameplay.Ability.Throw",DevComment="")
+GameplayTagList=(Tag="Gameplay.Ability.WallRun",DevComment="")
+GameplayTagList=(Tag="Gameplay.Effect.Damage",DevComment="")
+GameplayTagList=(Tag="Gameplay.Effect.StaminaDrain",DevComment="")
+GameplayTagList=(Tag="GameplayCue.Blink.Start",DevComment="")
+GameplayTagList=(Tag="GameplayCue.Clone.Effect",DevComment="")
+GameplayTagList=(Tag="GameplayCue.Grapple.Cable",DevComment="")
+GameplayTagList=(Tag="GameplayCue.newBlink",DevComment="")
+GameplayTagList=(Tag="GameplayCue.newBlink.start",DevComment="")
+GameplayTagList=(Tag="State.Clone.Active",DevComment="")
+GameplayTagList=(Tag="State.Clone.CanUse",DevComment="")
+GameplayTagList=(Tag="State.Clone.End",DevComment="")
+GameplayTagList=(Tag="Status.Damage.OverTime",DevComment="")
+GameplayTagList=(Tag="Status.Stamina.Regen",DevComment="")

